[core]
port = "29800"
slack_url = "https://hooks.slack.com/services/..." # if you use Legacy Incoming Webhooks
slack_token = "xoxb-00000-00000-xxxxxxxxxxx"       # post messages as Slack App Bot User

[[tags]]
tag = "general"
channel = "#general"

[[tags]]
tag = "random"
channel = "#random"
username = "slackboard"
icon_emoji = ":clipboard:"
parse = "full"

[log]
access_log = "stdout"
error_log = "stderr"
level = "error"
